import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#212529] text-[#DEE2E6] max-w-6xl mx-auto">
        {children}
      </body>
    </html>
  )
}
